### ISSUE TITLE
Capture partial packets

### ISSUE THREAD

**Issue by kirianto** [wdomski/SX1278#8]
Hi, I am working on partial packet recovery with LoRa. I am still new to LoRa technologies and I am wondering if your code could capture partial packets (i.e. packets with error CRCs)? 

I appreciate your help.

**Comment by wdomski** [comment]
Hi! Yes something like this is possible. You need to disable automatic 
CRC check. This can be done in initialization function.

Presence of CRC check will impact the preamble of LoRa package. I have 
never tested for this, however, it should work. Please leave a comment 
with your results.

Best regards,

Wojciech Domski

domski.pl | blog.domski.pl

W dniu 09.11.2021 o 05:37, Kurniawan Irianto pisze:
